server:
  port: 8080
spring:
  application:
    name: eureka-service
  boot:
    admin:
      client:
        url:
        - http://localhost:8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    prefer-ip-address: true