server:
 port: 1298

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
 
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/project_management
    username: root
    password: root
    
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
      
  data:
    mongodb:
      host: localhost
      port: 27017
      database: project
      
  application:
    name: project-management
  
     